name: khabir
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6

  # Network
  dio: ^5.3.2

  change_app_package_name: ^1.1.0
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0

  # Utilities
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  intl: ^0.20.2
  url_launcher: ^6.2.1

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0 # Using more stable version

  # OTP & Validation
  pin_code_fields: ^8.0.1

  # UI Enhancements
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.7.0
  socket_io_client: ^2.0.3+1

  flutter_launcher_icons: "^0.14.4"

  # PDF & File Handling
  flutter_pdfview: ^1.4.1+1
  file_picker: ^8.0.0+1

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
